---
# Ansible Host Scanner by James Kayser
- hosts: localhost
  gather_facts: false

  vars:
   msg: |
              Check the readme.md file for instructions on how to install and use this script.
              Certain tasks require sudo. To run as sudo, execute the following.
                 ansible-playbook host-reporter.yml --ask-become-pass

              If generating a report, look in your home directory for the html file output
              If using the list option, make sure you enter your list of ip addresses
              in the ip-list.txt file included with this playbook

  tasks:
    - name: Garbage Collection
      file:
        path: ./scan-output.xml
        state: absent

    - name: "Instructions"
      debug:
        msg: "{{ msg.split('\n') }}"

- hosts: localhost
  any_errors_fatal: false
  gather_facts: true
  roles:
    - role: scan

  vars_prompt:

  - name: "dependency_check"
    prompt: "Run Dependency Checks (good idea if first run)?  y|n"
    private: no
    default: 'n'

  - name: "scan_type"
    prompt: "Enter type of scan  ping|port|os|mtu|trace (ping sweep|tcp port scan|os detection|path mtu|traceroute)"
    private: no
    default: 'ping'

  - name: "target_hosts"
    prompt: "Enter subnet in CIDR notation, host IP, or type the word  list  for ip-list.txt input"
    private: no
    default: 'list'

  - name: "create_report"
    prompt: "Create HTML Report?  y|n"
    private: no
    default: 'n'
